pre-commit:
  jobs:
    - name: Go Format
      glob: "*.go"
      run: go fmt ./... && git diff --exit-code --quiet

    - name: Go Lint
      glob: "*.go"
      group:
        jobs:
          - run: go vet ./...
          - run: go tool revive ./...
          - run: go tool staticcheck ./...

    - name: Go Test
      glob: "*.go"
      run: go test ./...

    - name: Proto
      glob: "configs/message.proto"
      run: protoc --go_out=./pkg configs/message.proto && git diff --exit-code --quiet pkg

    - name: Actions Lint
      glob: ".github/workflows/*.yml"
      run: actionlint
