// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: configs/message.proto

package loki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*Stream              `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_configs_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_configs_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_configs_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *Message) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        string                 `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Hash          uint64                 `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_configs_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_configs_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_configs_message_proto_rawDescGZIP(), []int{1}
}

func (x *Stream) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Stream) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Stream) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type Entry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line               string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	StructuredMetadata []*Metadata            `protobuf:"bytes,3,rep,name=structuredMetadata,proto3" json:"structuredMetadata,omitempty"`
	Parsed             []*Metadata            `protobuf:"bytes,4,rep,name=parsed,proto3" json:"parsed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_configs_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_configs_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_configs_message_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Entry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Entry) GetStructuredMetadata() []*Metadata {
	if x != nil {
		return x.StructuredMetadata
	}
	return nil
}

func (x *Entry) GetParsed() []*Metadata {
	if x != nil {
		return x.Parsed
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_configs_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_configs_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_configs_message_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_configs_message_proto protoreflect.FileDescriptor

const file_configs_message_proto_rawDesc = "" +
	"\n" +
	"\x15configs/message.proto\x12\x04loki\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\aMessage\x12&\n" +
	"\astreams\x18\x01 \x03(\v2\f.loki.StreamR\astreams\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"[\n" +
	"\x06Stream\x12\x16\n" +
	"\x06labels\x18\x01 \x01(\tR\x06labels\x12%\n" +
	"\aentries\x18\x02 \x03(\v2\v.loki.EntryR\aentries\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\x04R\x04hash\"\xbd\x01\n" +
	"\x05Entry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12>\n" +
	"\x12structuredMetadata\x18\x03 \x03(\v2\x0e.loki.MetadataR\x12structuredMetadata\x12&\n" +
	"\x06parsed\x18\x04 \x03(\v2\x0e.loki.MetadataR\x06parsed\"4\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\aZ\x05/lokib\x06proto3"

var (
	file_configs_message_proto_rawDescOnce sync.Once
	file_configs_message_proto_rawDescData []byte
)

func file_configs_message_proto_rawDescGZIP() []byte {
	file_configs_message_proto_rawDescOnce.Do(func() {
		file_configs_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_message_proto_rawDesc), len(file_configs_message_proto_rawDesc)))
	})
	return file_configs_message_proto_rawDescData
}

var file_configs_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_configs_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: loki.Message
	(*Stream)(nil),                // 1: loki.Stream
	(*Entry)(nil),                 // 2: loki.Entry
	(*Metadata)(nil),              // 3: loki.Metadata
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_configs_message_proto_depIdxs = []int32{
	1, // 0: loki.Message.streams:type_name -> loki.Stream
	2, // 1: loki.Stream.entries:type_name -> loki.Entry
	4, // 2: loki.Entry.timestamp:type_name -> google.protobuf.Timestamp
	3, // 3: loki.Entry.structuredMetadata:type_name -> loki.Metadata
	3, // 4: loki.Entry.parsed:type_name -> loki.Metadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_configs_message_proto_init() }
func file_configs_message_proto_init() {
	if File_configs_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_message_proto_rawDesc), len(file_configs_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_message_proto_goTypes,
		DependencyIndexes: file_configs_message_proto_depIdxs,
		MessageInfos:      file_configs_message_proto_msgTypes,
	}.Build()
	File_configs_message_proto = out.File
	file_configs_message_proto_goTypes = nil
	file_configs_message_proto_depIdxs = nil
}
